services:
    cobalt-api:
        image: ghcr.io/imputnet/cobalt:10

        init: true
        read_only: true
        restart: unless-stopped
        container_name: cobalt-api

        ports:
            - 9000:9000

        environment:
            API_URL: "https://api.url.example/"

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

        networks:
            - botnet

    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    bot:
        build: .
        restart: unless-stopped
        container_name: wiikotbot
        depends_on:
            - cobalt-api
        env_file:
            - .env
        volumes:
            - ./database.db:/app/database.db
            - ./videos:/app/videos
            - ./SF-Pro.ttf:/app/SF-Pro.ttf
        networks:
            - botnet

networks:
    botnet:
        driver: bridge